#!/usr/bin/python3

from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QUrl
from PySide2.QtGui import QIcon
from PySide2.QtQml import QQmlApplicationEngine

import sys
import DpkgUnlocker

app = QApplication()
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
dpkgUnlockerBridge=DpkgUnlocker.DpkgUnlocker()
context.setContextProperty("dpkgUnlockerBridge", dpkgUnlockerBridge)

url = QUrl("/usr/lib/python3/dist-packages/dpkgunlockergui/rsrc/dpkg-unlocker.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/dpkg-unlocker-gui.svg"));
ret=app.exec_()
del engine
del app
sys.exit(ret)

